# Stores configuration data. 
# Many of these options can be specified from the command line executable
#   but it’s easier to specify them here so you don’t have to remember them.

# [Themes](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme)

# [https://pages.github.com/themes/]
# [https://github.com/pages-themes/cayman?tab=readme-ov-file]

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one