# Stores configuration data. 
# Many of these options can be specified from the command line executable
#   but it’s easier to specify them here so you don’t have to remember them.

# [Themes](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme)

remote_theme: abhinavs/moonwalk
# remote_theme: THEME-NAME
favicon: "./logo.png" # relative path to site's favicon

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts